language: node_js

before_install:
  - "npm install npm -g"

node_js:
  - "stable"
  - "8"
  - "10"

script:
  - npm run test

deploy:
  - provider: npm
    email: 'devmonk@mediamonks.com'
    api_key: $NPM_TOKEN
    on:
      tags: true
      node: 'stable'
    skip_cleanup: true
